config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :relationships
  devise_for :locations
  devise_for :application_records
  devise_for :notes
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'notes#show'
  get '/testing' => 'testing#testing', as: :testing
  get '/note/exec_int/' => 'notes#exec_int', as: :exec_int
  get '/note/add_birth_and_death' => 'notes#add_birth_and_death', as: :add_b_d
  get '/note/chain' => 'notes#chain', as: :chain
  get '/note/refresh' => 'notes#refresh', as: :refresh
  get '/note/refresh_quick' => 'notes#refresh_quick', as: :refresh_quick
  get '/note/read/:id' => 'notes#read', as: :read, :defaults => { id: '66' }
  get '/note/:id' => 'notes#show', as: :notes, :defaults => { id: '66' }
  get '/note/testing' => 'notes#testing', as: :notes_testing
  get '/note/:id' => 'notes#show', as: :note
  get '/locations/search' => 'locations#search', as: :locations_search
  get '/locations/search_results' => 'locations#show', as: :locations
  get '/special/spreadsheet/import' => 'special#spreadsheet_import'
  get '/special/spreadsheet/warning' => 'special#spreadsheet_warning', as: :siw
  get '/relationship/att_note' => 'relationships#att_note', as: :att_rel_note
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/note.rb
# frozen_string_literal: true

# !! for later refactoring !!
# keep in mind it may be better (better than relatives build)
# to start at the join model Relationship
#
# validator
class NoteValidator < ActiveModel::Validator
  def validate(note)
    deps = note.depends.full
    note.errors.add :base, 'self reference' if deps.include?(note.id)
  end
end

# the note model
class Note < ApplicationRecord
  # located in app/model/concerns
  include NoteAdmin
  has_many :relationship_notes, class_name: 'Relationship', foreign_key: :note_id
  has_many :parent_relationships,
           class_name: 'Relationship', foreign_key: :child_id,
           autosave: false
  has_many :child_relationships,
           class_name: 'Relationship', foreign_key: :parent_id,
           autosave: false
  has_many :children,
           through: :child_relationships,
           foreign_key: :parent_id, autosave: false
  has_many :parents,
           through: :parent_relationships, foreign_key: :child_id,
           autosave: false
  has_and_belongs_to_many :locations, autosave: false

  validates_with NoteValidator
  # attr_accessor :relationship
  # attr_accessor :flash_notice

  # # called by Relationship and controller
  # def self.tbc(note_id = nil)
  #   Tbc.append(note_id)
  # end

  def tags
    puts 'tags'
    ts = self[:tags]
    # this needs to be somewhere else!!
    # ts.push('tag') if child_relationships.length > 100
    puts 'done tags'
    ts
  end

  def self.tag_tags
    p_ids = Relationship.group(:parent_id)
                        .having('count(parent_id) > 100').select(:parent_id)
                        .map(&:parent_id)

    new_tag_notes = where("'tag' != all(tags)").where(id: p_ids)
    new_tag_notes.each do |n|
      n.tags += ['tag']
      n.save
    end

    old_tag_notes = where("'tag' = any(tags)").where.not(id: p_ids)
    old_tag_notes.each do |n|
      n.tags -= ['tag']
      n.save
    end
    p_ids
  end

  def date
    return locations[0].area_datetime.date_x if locations.any?
    created_at
  end

  def relatives(sf_name = nil)
    @relatives || rebuild_relatives(sf_name)
  end

  # made for post spreadsheet import
  # sort by sort field
  def rebuild_relatives(sf_name = nil)
    puts 'rebuild_relatives'
    @relatives = rel_build.uniq
    @relatives = @relatives.sort_by { |rel| rel.sort_field(sf_name) || '' } if sf_name
    @relatives
    
    # @relatives = rel_build.uniq.sort_by { |rel| rel.child.send(stf) }
  end

  # made for search
  def relatives_unsaved(rels)
    @relatives = []
    rels[0..300].each do |rel|
      new_r = Relationship.new(
        parent_id: id,
        child_id: rel.id
      )
      @relatives.push(new_r)
    end
  end

  def rel_build
    puts 'rel_build'
    rs = child_relationships.reload
    puts 'rel_build parent'
    parent_rs = parent_relationships.reload
    # i can put flip back, not the prob
    rs += parent_rs.each { |pr| pr[:child_id] = pr[:parent_id] } # (&:flip)
    puts 'done rebuild'
    rs
  end

  def rev_magic_pos
    puts 'rev_magic_pos'
    ns = Note.where('array[or_ids] && array[(?)]', [id])
    ns = ns.or(Note.where('array[and_ids] && array[(?)]', [id]))
    ns = ns.or(Note.where('array[relative_ids] && array[(?)]', [id]))
    ns
  end

  def self.pg_array(ary)
    ary.to_s.tr('[]"', '')
  end

  def self.pg_array_i(ary)
    ary
    # ary.to_s.tr('[]"\'', '')
  end

  def self.rev_magic_group_pos(notes)
    puts 'rev_magic_group_pos'
    return [] unless notes.any?
    # n_ids = Note.pg_array_i(notes.map(&:id))
    n_ids = notes.map(&:id)
    ns = Note.where('array[or_ids] && array[?]', n_ids)
    ns = ns.or(Note.where('array[and_ids] && array[?]', n_ids))
    ns = ns.or(Note.where('array[relative_ids] && array[?]', n_ids))
    ns = ns.where("'tag' != all(tags)")
    ns
  end

  def self.rev_magic_group(notes)
    puts 'rev_magic_group'
    ns = rev_magic_group_pos(notes)
    n_ids = notes.map(&:id)
    ns = ns.or(Note.where('array[not_ids] && array[?]', n_ids))
    ts = Note.pg_array(notes.map(&:tags).flatten.compact.uniq)
    ns = ns.or(Note.where('array[(?)] && array[(filter_tags)]', ts))
    ns
  end

  def rev_magic
    ns = rev_magic_pos
    ns = ns.or(Note.where('array[not_ids] && array[(?)]', [id]))
    ns = ns.or(
      Note.where('array[(?)] && array[(filter_tags)]', tags.to_s.tr('[]"', ''))
    )
    ns
  end

  def short_refresh
    puts 'short_refresh'
    Note.find(depends.all).each(&:refresh_magic)
    Note.refresh_magic
  end

  def magical?
    depends.all.any? ||
      self[:having_count].present? ||
      self[:magic].present? ||
      self[:filter_tags].any?
  end

  def depends
    Depends.new(self)
  end

  def refresh
    # i = refresh_magic
    # while c < 10 && i > 0
    Abc.append(id)
    ns = Note.where(id: depends.full)
    ns += rev_magic
    ns.uniq.each(&:refresh_magic)
    refresh_magic
  end

  def refresh_magic
    puts "RUNNING MAGIC #{id} #{name}"
    return 0 if depends.all.empty? && self[:filter_rname].empty?
    rels = Rels.new(self)
    rels.update_relatives
    # update_relatives(rels)
  end

  def img
    self[:img] || ''
  end

  def img_small
    self[:img32] || img
  end

  def ext_link_name
    self[:ext_link_name]
  end
end

# which notes a magic note "depends" on fro relationships.
class Depends
  def initialize(note)
    @note = note
    @deps_full = []
  end

  def all
    puts 'Depends.all'
    (pos + @note.not_ids).uniq
  end

  def pos
    puts 'Depends.pos'
    (@note.or_ids + @note.and_ids + @note.relative_ids).uniq
  end

  def depends_deeper
    puts 'depends_deeper'
    Note.where(id: @deps_full).map { |n| n.depends.all }.flatten.uniq - @deps_full
  end

  # will need fixing also
  def depends_deeper_pos
    Note.where(id: deps_full_pos).map(&:pos).flatten.uniq - @deps_full
  end

  def full_pos
    puts 'Depends.full_pos'
    deps_new = pos
    @deps_full = deps_new
    while deps_new.any?
      deps_new = depends_deeper_pos
      @deps_full += deps_new
      @deps_full = @deps_full.uniq
    end
    @deps_full
  end

  def self.depends_deeper_group
    Note.where(id: @deps_full).map { |n| n.depends.all }.flatten.uniq - @deps_full
  end

  def self.full_group(notes)
    deps_new = notes.map { |note| note.depends.all }.uniq
    @deps_full = deps_new
    while deps_new.any?
      deps_new = depends_deeper_group
      @deps_full += deps_new
      @deps_full = @deps_full.uniq
    end
    @deps_full
  end

  def full
    puts 'Depends.full'
    deps_new = all
    @deps_full = deps_new
    while deps_new.any?
      deps_new = depends_deeper
      @deps_full += deps_new
    end
    @deps_full
  end
end

# to be checked
# keeps a list for future checking, dnr.
class Tbc
  def self.list
    @tbc
  end

  def self.append(note_id)
    puts 'Tbc.append'
    Abc.append(note_id)
    @tbc ||= []
    @tbc.push(note_id)
    @tbc = @tbc.compact.flatten.uniq
    @tbc
  end

  def self.remove(note_id)
    @tbc -= [note_id]
  end

  def self.full_check
    @tbc ||= []
    cnt = 0
    while @tbc.any? || Abc.list.any?
      cnt += 1
      check_tbc(cnt) if @tbc.any?
      Abc.check unless @tbc.any?
    end
    puts @tbc.length
  end

  def self.check_tbc(cnt)
    puts 'check_tbc'
    ts = Note.tag_tags
    @tbc -= ts
    tbcs = Note.where(id: @tbc.sort)
    # tbcs.inject(tbcs) { |t_a, note| t_a + note.rev_magic_pos }.uniq
    tbcs = Note.rev_magic_group_pos(tbcs).uniq.sort + tbcs
    tbcs -= Note.find(ts)

    tbcs.each_with_index do |note, ind|
      next_tbc(note, cnt, tbcs.length - ind)
    end
    # return unless @tbc.empty?
    # puts @run_once.length.to_s.light_green
    # puts @run_twice.length.to_s.light_yellow
    # puts @run_thrice.length.to_s.yellow
    # puts @run_too_much.to_s.red
    # @run_too_much
  end

  def self.next_tbc(note, cnt, rmnd)
    puts 'next_tbc'
    [note.id].each do |n_id|
      Tbc.remove(n_id)
      Abc.append(n_id)
    end
    # Tbc.remove(note.id)
    # does this go here????
    # Abc.append(note.id)
    puts "\n\n********************* NEXT TBC ************************\n\n
    #{rmnd} #{cnt}\n\n".light_green
    note.refresh_magic if note.methods.include?(:refresh_magic)
    # deletions
  end

  def self.final_check
    puts 'final_check'
    Abc.check
  end
end

# already been checked
# recheck abc, mostly for remove olds
class Abc
  def self.list
    @abc
  end

  def self.append(tbc)
    @abc ||= []
    @abc += [tbc]
    @abc = @abc.uniq
  end

  def self.check
    return unless @abc.any?
    abc_l = Note.find(list)
    # abc_l.inject(abc_l) { |tbc, chk| tbc + chk.rev_magic }
    # .uniq.each(&:refresh_magic)
    abcs = abc_l + Note.rev_magic_group(abc_l)
    # abcs += Note.where(id: abc_l.map { |nt| nt.depends.full })
    abcs += Note.where(id: Depends.full_group(abc_l))
    abcs.uniq.sort.each_with_index do |note, ind|
      puts "ABC Check #{abcs.length - ind}: #{note.id} #{note.name}".light_green
      note.refresh_magic
    end
    @abc = []
  end
end

# a class for updating and checking the relatives of a note
class Rels
  def initialize(note)
    @rels = []
    @note = note
    rels_collection
    magic_filter
    @ids = @rels.map(&:child_id)
  end
  attr_reader :note, :rels

  def rels_collection
    magic_ands if @note[:and_ids].any?
    magic_ors
    magic_relatives
  end

  def current_ids
    @current_ids ||= note.child_relationships.reload.map(&:child_id)
  end

  def magic_relatives
    return unless @note[:relative_ids].any?
    rs = Relationship.distant_relatives(@note.relative_ids)
    # rs = Note.where(id: relative_ids).map(&:relatives).flatten
    # name needs to stay the same for future filtering
    rs = rs.map do |rel|
      Relationship.new(
        name: rel.name,
        parent_id: @note.id,
        child_id: rel.child_id
      )
    end
    @rels += rs
  end

  def magic_ors
    return unless @note[:or_ids].any?
    rs = @note.or_ids.inject([]) do |total, or_id|
      total + Note.find(or_id).relatives
    end

app/controllers/notes_controller.rb
# frozen_string_literal: true

# the notes controller
class NotesController < ApplicationController
  before_action :set_note, :check_note, :set_sortfield, except: :exec_int

  def index; end

  def show
    # relatives builds instance variable based on sortfield
    # @note.relatives(@sortfield)
  end

  def read
    @note.relatives('rel_name')
    render layout: 'read'
  end

  def chain
    @note.chain
    render 'show'
  end

  def add_birth_and_death
    birth = Relationship.new
    birth.name = 'birth'
    birth_note = Note.new(text: '')
    birth_note.name = "birth of #{@note.name}}"
    birth_note.save
    birth.parent_id = @note.id
    birth.child_id = birth_note.id
    birth.save
    death_note = Note.new(text: '')
    death_note.name = "death of #{@note.name}}"
    death_note.save
    Relationship.create(name: 'death', parent_id: @note.id, child_id: death_note.id)
    redirect_back(fallback_location: :root)
  end

  def refresh
    @note.refresh
    Tbc.append(@note.id)
    Tbc.full_check
    # (1..100).each do |cnt|
    #   break if Tbc.list.empty?
    #   Tbc.check_tbc(cnt)
    # end
    puts 'Still Remaining: ' + Tbc.list.length.to_s.red
    puts 'COMPLETE'.light_green if Tbc.list.empty?
    redirect_back(fallback_location: :root)
  end

  def refresh_quick
    @note.refresh_magic
    redirect_back(fallback_location: :root)
  end

  def exec_int
    fork { system("libreoffice -o public/int_files/#{params[:int_file]}") }
    redirect_back(fallback_location: :root)
  end

  private

  def set_sortfield
    @sortfield = params[:sortfield] || 'rel_name'
  end

  def set_note
    if params[:q]
      params[:q]['name_cont_all'] = params[:q]['name_cont_all'].split(' ')
      params[:q]['text_cont_all'] = params[:q]['text_cont_all'].split(' ')
    end

    if params[:nikud_search]
      @note = Note.new
      @note.name = 'search results'
      children = Note.where("regexp_replace(text, '[\u0591-\u05c7]', '', 'g') ilike '%#{params[:nikud_search]['word']}%'")
      children = children.where("name ilike '%#{params[:nikud_search][:name]}%'")
      @note.children = children
    end

    @q = Note.ransack(params[:q]) # if params[:q]
    @note ||= if params[:q]
              search_results
            elsif params[:id].to_i > 0
              Note.find(params[:id])
            else
              Note.find(66)
            end
  end

  def search_results
    @search_results = @q.result # .includes(:locations)
    note = Note.new
    note.name = 'Search Results'
    note.relatives_unsaved(@search_results)
    note
  end

  # this needs to be done on mode, but being thorough
  def check_note
    return if user_signed_in?
    if @note.is_private
      redirect_to :root
    else
      # it kept writing to db
      note = Note.new
      note.attributes = @note.attributes
      note.children = @note.children.to_a.delete_if(&:is_private)
      note.parents = @note.parents.to_a.delete_if(&:is_private)
      @note = note
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  # for local ip
  require 'socket'
  def show_area_datetime(location)
    d_x = location.area_datetime.date_x
    d_x = d_x.strftime('%b %-d, %Y') if d_x
    t_x = location.area_datetime.time_x
    t_x = t_x.strftime('%l:%M %P') if t_x
    d_y = location.area_datetime.date_y
    d_y = d_y.strftime('%b %-d, %Y') if d_y
    t_y = location.area_datetime.time_y
    t_y = t_y.strftime('%l:%M %P') if t_y
    "#{d_x} #{t_x} - #{d_y} #{t_y}"
  end

  def openstreet_src(loc)
    p = [lox(loc).to_s, lax(loc).to_s, loy(loc).to_s, lay(loc).to_s].join('%2C')
    "https://www.openstreetmap.org/export/embed.html?bbox=#{p}&layer=mapnik"
  end

  def openstreet_href(loc)
    # "https://www.openstreetmap.org/#map=12/51.5370/9.8839&amp;layers=ND"
    m = openstreet_map_number((lay(loc) - lax(loc)))
    # lax = location.area_latitude.x
    # lay = location.area_latitude.y
    la = (lay(loc) + lax(loc)) / 2
    lo = (loy(loc) + lox(loc)) / 2
    "https://www.openstreetmap.org/#map=#{m.to_i}/#{la}/#{lo}&amp;layers=ND"
  end

  def lax(loc)
    loc.area_latitude.x
  end

  def lay(loc)
    loc.area_latitude.y
  end

  def lox(loc)
    loc.area_longitude.x
  end

  def loy(loc)
    lo = loc.area_longitude.y
    lo = loc.area_longitude.y + 360 if loc.area_longitude.y < loc.area_longitude.x
    lo
  end

  def openstreet_map_number(la_size)
    case la_size * 10
    when 0..5
      12
    when 5..9
      9
    when 9..10
      8
    when 10..50
      7
    when 50..100
      6
    when 100..150
      5
    when 150..300
      4
    else
      3
    end
  end

  def local_machine?
    remote_ip == '127.0.0.1'
  end

  def remote_ip
    # Net::HTTP.get(URI.parse('http://checkip.amazonaws.com/')).squish
    request.remote_ip # 127.0.0.1
  end

  def local_ip
    # 172.20.164.82
    # turn off reverse DNS resolution temporarily
    orig = Socket.do_not_reverse_lookup
    Socket.do_not_reverse_lookup = true

    UDPSocket.open do |s|
      s.connect '64.233.187.99', 1
      s.addr.last
    end
  ensure
    Socket.do_not_reverse_lookup = orig
  end
end

app/views/notes/_card.html.haml
= image_tag note.img, class: 'show_note card-img-top center'
#card_body.card-body
  %h5.card-title= link_to(note.name, note)
  %h6.card-subtitle.mb-2= note.summary
  %p.card-text= note.text.to_s.html_safe
  -# = link_to(note.ext_link_name.present? ? note.ext_link_name : note.ext_link, note.ext_link, class: 'btn btn-primary') if note.ext_link.present?
  %ul
    - note.relatives.each do |r_r|
      - next if r_r.child.magical? || r_r.name == nil || r_r.name == ''
      %li
        = link_to "#{r_r.name}: #{r_r.child.name}", notes_path(id: r_r.child.id)

app/views/notes/index.html.haml
-@note = Note.find(39)
=form_for @note do |f|
  = f.trix_editor :text

app/views/notes/read.html.haml
- # needs to be set up properly
- ignore_list = ['מתוכן']

- card_styles = @note.tags.push('card')
- card_styles.push('private') if @note.is_private
#main{class: card_styles}
  = render('card', note: @note) 
#children
  %table.table
    %tbody
    - @note.relatives.each do |relative|
      - next if relative.child.magical?
      -# binding.pry
      - r_styles = relative.child_tags
      - r_styles.push('private') if relative.child_is_private
      %tr
        %th{class: relative.card_style }
          = relative.name
      %tr{class: relative.card_style }
        %td
          = render('card', note: relative.child) unless ignore_list.include?(relative.name)
      %tr
        %td
          - if relative[:note_id]
            = render('card', note: relative.note)

app/views/notes/show.html.haml
= render('layouts/adv_search') if @q
- card_styles = @note.tags.push('card')
- card_styles.push('private') if @note.is_private
#main{class: card_styles}
  = image_tag @note.img, class: 'show_note card-img-top'
  #card_body.card-body
    %h5.card-title= @note.name
    %h6.card-subtitle.mb-2= @note.summary
    %p.card-text= @note.text.to_s.html_safe
    = link_to(@note.ext_link_name.present? ? @note.ext_link_name : @note.ext_link, @note.ext_link, class: 'btn btn-primary') if @note.ext_link.present?
    - if @note.int_link.present?
      = link_to("Download #{@note.int_link}", "/int_files/#{@note.int_link}")
      %br
      = link_to("Launch #{@note.int_link}", exec_int_path(int_file: @note.int_link)) if local_machine?
    %br
    = link_to('read', read_path(@note.id)) if @note.id
    #locations.accordion
    - @note.locations.each_with_index do |location, i|
      - puts 'do locations'
      #card.card{ id: i}
        #heading.card-header{ id: "#{i}" }
          %h5.mb-0
            %button.btn.btn-link.collapsed{ type: 'button', "data-toggle": "collapse", "data-target":"#collapse_#{i}", "aria-expanded": "false", 'aria-controls': "collapse_#{i}", onclick: "var ifr=document.getElementById('collapse_#{i}').getElementsByTagName('iframe')[0]; ifr.src=ifr.src;" }
              = location.name
        #collapse.collapse{ id: "#{i}", "area-labelledby": "heading_#{i}", "data-parent": "#locations" }
          #card.card-body{ id: "#{i}"}

            %iframe{ width: 425, height: 350, frameborder: 0, scrolling: "no",  style: "border: 1px solid black", src: openstreet_src(location)  }
            = link_to 'view larger map', openstreet_href(location)

            %ul
              %li= show_area_datetime(location)
              %li= "latitude #{location.area_latitude.x} - #{location.area_latitude.y}"
              %li= "longitude #{location.area_longitude.x} - #{location.area_longitude.y}"
    = link_to('edit', "/admin/note/#{@note.id}/edit", class: 'btn btn-primary bg-danger text-white') if user_signed_in?
    = link_to('refresh', refresh_path(id: @note.id)) if @note.depends.all.any? || @note.filter_rname.any?
    = link_to('quick refresh', refresh_quick_path(id: @note.id)) if @note.depends.all.any? || @note.filter_rname.any?
  #card_footer.card-footer.bg-info
    %tr
      %td
        = (@note.tags - ['card']).to_s
      %td
        = @note.updated_at

#relatives
  %table.table
    - if @note.id
      %th
        = "sort #{@note.relatives(@sortfield).count}"
        = link_to 'chain', chain_path(id: @note.id)
      %th
        = link_to 'name', notes_path(id: @note.id, sortfield: 'name')
      %th
        = @sortfield
      %th
        = link_to 'summary', notes_path(id: @note.id, sortfield: 'summary')
      %th
        = link_to 'rel name', notes_path(id: @note.id, sortfield: 'rel_name')

    %tbody
      %tr
        %td{colspan: 5}
          -#= select :filter, :select, ['filter'] + @note.relatives.map(&:child_relatives).flatten.map(&:child_name).flatten.uniq.sort.map(&:downcase), {}, {class: 'js-onchange', js_funct: 'showhideSelect', 'js_var': 'filter_select'}
          - puts '@note.relatives.map # for filter'
          = select :filter, :select, ['filter'] + @note.relatives.map(&:card_style).flatten.uniq.sort, {}, {class: 'js-onchange', js_funct: 'showhideSelect', 'js_var': 'filter_select'}
      %tr
        - puts '@note.relatives.map(&:child_id)'
        %td{colspan: 5}
          = @note.relatives.map(&:child_id).sort.to_s
      %tr
        - puts 'starting @note.dependencies_full'
        %td{colspan: 5}
          = @note.depends.full
      - puts 'starting @note.relatives'
      - @note.relatives(@sortfield).each do |relative|
        - puts 'do @note.relatives'
        - relative.child_id = relative.parent_id if relative.child_id == @note.id
        %tr{class: relative.card_style}
          %td.show_note_relative_image{ style: "width: 10%;" }= image_tag relative.child_img_small, class: 'show_note_relative'
          %td= link_to relative.child_name, notes_path(id: relative.child_id), class: 'btn btn-sm btn-light'
          %td= relative.child_text[0..50].html_safe if relative.child_text.present?
          %td= relative.child_summary
          %td
            - if relative.note_id.present?
              = link_to relative.name, notes_path(id: relative.note_id)
            - else
              = relative.name
          %td= link_to 'edit r', "/admin/relationship/#{relative.id}/edit"

app/views/notes/testing.html.haml
%h1 TESTING
= trix_editor_tag :chicken, :monkey