config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :relationships
  devise_for :locations
  devise_for :application_records
  devise_for :notes
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'notes#show'
  get '/testing' => 'testing#testing', as: :testing
  get '/note/exec_int/' => 'notes#exec_int', as: :exec_int
  get '/note/add_birth_and_death' => 'notes#add_birth_and_death', as: :add_b_d
  get '/note/chain' => 'notes#chain', as: :chain
  get '/note/refresh' => 'notes#refresh', as: :refresh
  get '/note/refresh_quick' => 'notes#refresh_quick', as: :refresh_quick
  get '/note/read/:id' => 'notes#read', as: :read, :defaults => { id: '66' }
  get '/note/:id' => 'notes#show', as: :notes, :defaults => { id: '66' }
  get '/note/testing' => 'notes#testing', as: :notes_testing
  get '/note/:id' => 'notes#show', as: :note
  get '/locations/search' => 'locations#search', as: :locations_search
  get '/locations/search_results' => 'locations#show', as: :locations
  get '/special/spreadsheet/import' => 'special#spreadsheet_import'
  get '/special/spreadsheet/warning' => 'special#spreadsheet_warning', as: :siw
  get '/relationship/att_note' => 'relationships#att_note', as: :att_rel_note
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_adv_search.html.haml
-#adv_search_container.container
  #the_row.row
    #md12.col-md-12
      #adv-search.input-group
        %input.form-control{type: 'text', placeholder: 'search'}
        #ig.input-group-text
          #bg.btn-group{role: 'group'}
            #dd.dropdown.dropdown-lg
              %button.btn.dropdown-toggle{'data-toggle': 'dropdown', 'aria-expanded':'false'}
                #ddmenu.dropdown-menu.dropright{role: 'menu'}
                  %form{role: 'form'}
                    #fg_name.form-group
                      %label{'for': 'contain'} Name
                      %input.form-control{type: 'text'}
              %button.btn.btn-primary{type: 'button'}
                %span.glyphicon.glyphicon-search{'aria-hidden': 'true'}

= search_form_for @q do |f|
  -#search_form_row.row
    #search_form_row_col1.col
      = f.label :name_cont
      = f.search_field :name_cont # , placeholder: 'Search for a Note name'
    #search_from_row_col2.col
      = f.submit 'Search', class: 'btn btn-sm'
  #search_form_row.row
    #search_form_row_col3.col
      #adv_search_container.accordion
        #card.card
          #heading.card-header
            %button.btn.btn-sm.collapsed{ type: 'button', "data-toggle": "collapse", "data-target":"#adv_search", "aria-expanded": "false", 'aria-controls': "adv_search" }
              = 'Search'
          #adv_search.collapse{"area-labelledby": "heading", "data-parent": "#adv_search_container" }
            #card.card-body
              = search_form_for @q do |f|
                = f.search_field :name_cont_all, class: 'form-control', placeholder: 'Search for a Note name'
                %br/
                = f.search_field :summary_cont_all, class: 'form-control', placeholder: 'Search by summary'
                %br/
                = f.search_field :text_cont_all, class: 'form-control', placeholder: 'Search inside Note text'
                %br/
                = f.search_field :locations_name, class: 'form-control', placeholder: 'Search for a Location name'
                %br/
                = f.submit 'Search', class: 'btn btn-sm'
                %br/
                = link_to 'Search for a location', locations_search_path, class: 'btn btn-sm'
              %form{action: 'search_nekud'}
                = text_field :nikud_search, :word, placeholder: 'search nikud text'
                = text_field :nikud_search, :name, placeholder: 'name'
                = submit_tag 'Search'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= @note ? @note.name + ' - ZapafuUg' : 'ZapafUg'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all' # , 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application' # , 'data-turbolinks-track': 'reload'
  %body
    %header
      #header.container-fluid
        %p.notice= notice
        %p.alert= alert
        %nav.navbar
          %ul.nav.nav-pills
            %li.nav-item= link_to 'sign out', destroy_user_session_path, :method => :delete if user_signed_in?
    #page.container
      = yield

app/views/layouts/read.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= @note ? @note.name + ' - ZapafuUg' : 'ZapafUg'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all' # , 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application' # , 'data-turbolinks-track': 'reload'
  %body
    %header
      #header.container-fluid
        %p.notice= notice
        %p.alert= alert
    #page.container
      = yield

app/views/layouts/spreadsheet_import.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= 'spreadsheet import'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all' # , 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application' # , 'data-turbolinks-track': 'reload'
  %body
    %header
      #header.container-fluid
        %p.notice= notice
        %p.alert= alert
        %nav.navbar
          %ul.nav.nav-pills
            %li.nav-item= link_to 'sign out', destroy_user_session_path, :method => :delete if user_signed_in?
    #page.container
      = yield